name: Abandoned Labeler

on:
  schedule:
    - cron: "*/2 * * * *"

jobs:
  abandoned-labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Check for abandoned issues
        uses: actions/github-script@v6
        with:
          script: |
            const { owner, repo } = context.repo;
            const pendingLabel = "Pending";
            const abandonedLabel = "Abandoned";
            const timeThreshold = 2 * 60 * 1000; // 2 minutes in milliseconds

            const issuesResponse = await github.issues.listForRepo({
              owner,
              repo,
              labels: Pending,
              state: "open",
            });

            for (const issue of issuesResponse.data) {
              const updatedAt = new Date(issue.updated_at).getTime();
              const currentTime = new Date().getTime();

              if (currentTime - updatedAt > timeThreshold) {
                await github.issues.addLabels({
                  owner,
                  repo,
                  issue_number: issue.number,
                  labels: [Abandoned],
                });

                await github.issues.removeLabel({
                  owner,
                  repo,
                  issue_number: issue.number,
                  name: Pending,
                });

                await github.issues.createComment({
                  owner,
                  repo,
                  issue_number: issue.number,
                  body: "It's been more than 2 minutes since your last update. Could you provide an update?",
                });
              }
            }