name: Auto Assign Label
on:
  issues:
    types:
      - opened
jobs:
  auto-assign-label:
    runs-on: ubuntu-latest
    steps:
      - name: Get Team Members
        id: team-members
        run: echo "members=AlanRoth,felixif,shub8968,shub8881,Elifzeynepedman,deetewari,RamyaBill,fturizo" >> $GITHUB_ENV
      - name: Get Next Team Member
        id: next-member
        run: |
          members=($(echo "${{ env.members }}" | tr ',' '\n'))

          index=$(( (${GITHUB_RUN_NUMBER}-1) % ${#members[@]} ))

          next_member=${members[$index]}

          echo "next_member=$next_member" >> $GITHUB_ENV
      - name: Install @octokit/auth-token and @octokit/rest
        run: npm install @octokit/auth-token @octokit/rest
      - name: Add Open Label and Assign to Next Team Member
        uses: actions/github-script@v6
        with:
          script: |
            const { Octokit } = require("@octokit/rest");
            const { Auth } = require("@octokit/auth-token");
            
            const auth = new Auth({
              type: "token",
              token: process.env.GITHUB_TOKEN,
            });

            const octokit = new Octokit({ authStrategy: auth.strategy });

            octokit.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ['Open']
            });
            octokit.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              assignees: [`${{ env.next_member }}`]
            });
          github-token: ${{ secrets.GITHUB_TOKEN }}