name: Close abandoned issues
on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  abandoned-labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Close the abandoned issue
        uses: actions/github-script@v6
        with:
          script: |
            const { owner, repo } = context.repo;
            const abandonedLabel = "Abandoned";
            const timeThreshold = 5 * 60 * 1000 //5 * 24 * 60 * 60 * 1000; // 5 days in milliseconds
           
            const issuesResponse = await github.rest.issues.listForRepo({
              owner,
              repo,
              labels: abandonedLabel,
              state: "open",
            });
            
            for (const issue of issuesResponse.data) {
              const updatedAt = new Date(issue.updated_at).getTime();
              const currentTime = new Date().getTime();

              if (currentTime - updatedAt > timeThreshold) {
            
                await github.rest.issues.removeLabel({
                  owner,
                  repo,
                  issue_number: issue.number,
                  name: abandonedLabel,
                });

                await github.rest.issues.createComment({
                  owner,
                  repo,
                  issue_number: issue.number,
                  body: "Closing the Abandoned issue that has not been updated",
                });
                
                await github.rest.issues.update({
                  owner,
                  repo,
                  issue_number: issue.number,
                  state: "closed",
                });
              }
            }